services:
  discord-bot:
    container_name: discord-bot-bratensosse
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - discord.credentials:/app/discord.credentials
    restart: unless-stopped
    working_dir: /app